package com.base.simple.drools;/*这里的包路径可以不并写到相应的位置*/

import com.base.simple.drools.Person;/*这里引用的POJO必须是正确的*/

rule "boy"   /*规则名*/
    salience 1  /*优先级， 值越大，优先级越高*/
    when
        $p : Person(age > 0);
    then
        $p.setDesc("少年");
        retract($p);
end

rule "youth"
    salience 2
    when
        $p : Person(age > 12);
    then
        $p.setDesc("青年");
        retract($p);
end

rule "midlife"
    salience 3
    when
        $p : Person(age > 24);
    then
        $p.setDesc("中年");
        retract($p);
end

rule "old"
    salience 4
    when
        $p : Person(age > 60);
    then
        $p.setDesc("老年");
        retract($p);
end